# -*- coding: utf-8 -*-
"""capstone_ml.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q4-j4q_V6JTYLw7VuP-r4_stCpQ6b4lx

# Predictive Vehicle Maintenance System

## Machine Learning Pipeline

### 1. Data Collection Sources
- Car sensor data via On-board diagnostics (OBD-II)
- Historical vehicle breakdown data
- Kaggle Datasets (OBD-II datasets)
  - Features: 33 columns representing various vehicle sensor data

### 2. Key Predictive Models

#### Model 1: Failure Probability Prediction
- **Type**: Binary Classification
- **Algorithm**: Random Forest Classifier
- **Classification Categories**:
  - Normal Case
  - Problem Cases

#### Model 2: Trouble Code Classification
- **Type**: Multi-Classification
- **Algorithm**: Random Forest Classifier
- **Purpose**: Classify between 12 types of trouble codes
- **Key Question**: What is the probability of a failure occurring within the next X hours?

#### Model 3: Remaining Useful Life Prediction
- **Type**: Regression
- **Algorithm**: ExtraTreesRegressor
- **Purpose**: Predict remaining useful life of vehicle components

#### Model 4: Service Priority Assessment
- **Type**: Natural Language Processing
- **Model**: GPT-4
- **Key Question**: Which asset requires servicing most urgently?

### 3. Implementation
- Testing and deployment via Streamlit
- Handles imbalanced data scenarios
- Focus on model performance optimization

# Vehicle Data Processing Pipeline

## Overview

The `VehicleDataProcessor` class provided processes and analyzes vehicle diagnostic data by performing preprocessing steps such as data cleaning, feature transformation, and filtering. Below is a breakdown of its functionality and how it can be used:

### Features of `VehicleDataProcessor`
1. **Initialization**:
   - Accepts a CSV file path containing vehicle diagnostic data and reads it into a pandas DataFrame.

2. **Preprocessing (`preprocess_data`)**:
   - Cleans and transforms the dataset:
     - Fills missing values for `TROUBLE_CODES` with "normal" under specific conditions.
     - Drops rows with missing `TROUBLE_CODES`.
     - Removes unnecessary columns.
     - Converts relevant columns to numeric formats.
     - Handles missing values with mean imputation and interpolation.

3. **Cleaning Numeric Columns (`_clean_numeric_columns`)**:
   - Processes specific columns such as `SHORT TERM FUEL TRIM BANK 1`, `ENGINE_LOAD`, and others to ensure numeric consistency.

4. **Handling Missing Values (`_handle_missing_values`)**:
   - Fills missing values in numeric columns with their mean and interpolates other missing values.

5. **Filter for Specific Trouble Codes (`filter_trouble_codes`)**:
   - Extracts data rows corresponding to a specific trouble code.

---
"""

import numpy as np
import pandas as pd
import os
from google.colab import drive
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split
from sklearn.ensemble import (
    RandomForestClassifier,
    RandomForestRegressor,
    ExtraTreesRegressor
)
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

# Mount Google Drive
drive.mount('/content/drive')

# Define file path
file_path = '/content/drive/My Drive/capstone/exp1_14drivers_14cars_dailyRoutes.csv'

class VehicleDataProcessor:
    """
    A class to process and analyze vehicle diagnostic data.
    """

    def __init__(self, file_path):
        """
        Initialize the data processor with the file path.

        Parameters:
        -----------
        file_path : str
            Path to the CSV file containing vehicle data
        """
        self.data = pd.read_csv(file_path)
        self.processed_data = None

    def preprocess_data(self):
        """
        Perform all data preprocessing steps including cleaning and transforming.
        """
        # Create a copy of the original data
        self.processed_data = self.data.copy()

        # Handle DTC_NUMBER and TROUBLE_CODES
        mask = (self.processed_data['DTC_NUMBER'] == 'MIL is OFF0 codes') & \
               (self.processed_data['TROUBLE_CODES'].isna())
        self.processed_data.loc[mask, 'TROUBLE_CODES'] = 'normal'

        # Drop rows with missing TROUBLE_CODES
        self.processed_data.dropna(subset=['TROUBLE_CODES'], inplace=True)

        # Remove unnecessary columns
        columns_to_drop = [
            'TIMESTAMP', 'DTC_NUMBER', 'AUTOMATIC', 'EQUIV_RATIO', 'ENGINE_RUNTIME',
            'FUEL_TYPE', 'SHORT TERM FUEL TRIM BANK 2', 'FUEL_PRESSURE',
            'LONG TERM FUEL TRIM BANK 2', 'MAF', 'AMBIENT_AIR_TEMP', 'FUEL_LEVEL',
            'BAROMETRIC_PRESSURE(KPA)', 'VEHICLE_ID', 'MODEL', 'YEAR', 'MARK',
            'MONTHS', 'DAYS_OF_WEEK', 'MIN', 'VEHICLE_ID', 'INTAKE_MANIFOLD_PRESSURE',
            'CAR_YEAR'
        ]
        self.processed_data = self.processed_data.drop(columns_to_drop, axis=1)

        # Clean and convert numeric columns
        self._clean_numeric_columns()

        # Handle missing values
        self._handle_missing_values()

        return self.processed_data

    def _clean_numeric_columns(self):
        """
        Clean and convert numeric columns to proper format.
        """
        # Clean SHORT TERM FUEL TRIM BANK 1
        self.processed_data['SHORT TERM FUEL TRIM BANK 1'] = (
            self.processed_data['SHORT TERM FUEL TRIM BANK 1']
            .str.split("%")
            .str.get(0)
            .astype(float)
        )

        # Clean ENGINE_LOAD
        self.processed_data['ENGINE_LOAD'] = (
            self.processed_data['ENGINE_LOAD']
            .str.split("%")
            .str.get(0)
            .str.replace(',', '.')
            .astype(float)
        )

        # Clean THROTTLE_POS
        self.processed_data['THROTTLE_POS'] = (
            self.processed_data['THROTTLE_POS']
            .str.split("%")
            .str.get(0)
            .astype(float)
        )

        # Clean TIMING_ADVANCE
        self.processed_data['TIMING_ADVANCE'] = (
            self.processed_data['TIMING_ADVANCE']
            .str.split("%")
            .str.get(0)
            .str.replace(',', '.')
            .astype(float)
        )

        # Clean ENGINE_POWER
        engine_power_mapping = {'1,6': 1.6, '1,8': 1.8, '1,4': 1.4}
        self.processed_data['ENGINE_POWER'] = (
            self.processed_data['ENGINE_POWER']
            .replace(engine_power_mapping)
            .astype(float)
        )

    def _handle_missing_values(self):
        """
        Handle missing values in the dataset using mean imputation.
        """
        numeric_columns = [
            'SHORT TERM FUEL TRIM BANK 1',
            'ENGINE_POWER',
            'ENGINE_LOAD',
            'THROTTLE_POS',
            'TIMING_ADVANCE'
        ]

        for column in numeric_columns:
            mean_value = self.processed_data[column].mean()
            self.processed_data[column].fillna(mean_value, inplace=True)

        # Interpolate remaining missing values
        self.processed_data = self.processed_data.interpolate()

    def filter_trouble_codes(self, trouble_code):
        """
        Filter data for specific trouble codes.

        Parameters:
        -----------
        trouble_code : str
            The trouble code to filter for

        Returns:
        --------
        pd.DataFrame
            Filtered dataset containing only the specified trouble code
        """
        return self.processed_data[self.processed_data['TROUBLE_CODES'] == trouble_code]

# Usage
if __name__ == "__main__":
    # Initialize processor
    processor = VehicleDataProcessor(file_path)

    # Process data
    cleaned_data = processor.preprocess_data()
    data = cleaned_data.copy()
    data_1 = data.copy()
    data_2 = data.copy()

    # Filter for specific trouble codes
    filtered_data = processor.filter_trouble_codes("P0079P2004P3000")

    print("Data shape:", cleaned_data.shape)
    print("\nMissing values:\n", cleaned_data.isna().sum())
    print("\nFiltered data head:\n", filtered_data.head())

"""### Key Features of the `BinaryClassificationProcessor` Class

1. **Data Preparation**:
   - The class processes a DataFrame (`data`) containing vehicle information, including `TROUBLE_CODES`, which are encoded into binary values (`T_C` column).
   - The `prepare_target` method converts `TROUBLE_CODES` into binary form, where `normal` is mapped to `0` and any other value to `1`.

2. **Dataset Balancing**:
   - The `balance_dataset` method performs undersampling to balance the dataset, particularly addressing cases where the `normal` category might dominate. It ensures a balanced distribution for effective model training.

3. **Feature Preparation**:
   - The `prepare_features` method separates features and the target variable (`T_C`). It allows for dropping unnecessary or user-specified columns.

4. **Train-Test Split**:
   - The `split_data` method divides the dataset into training and testing subsets, ensuring reproducibility with a specified random state.

5. **Model Training**:
   - The `train_model` method trains a Random Forest classifier with customizable parameters.

6. **Model Evaluation**:
   - The `evaluate_model` method assesses the model's performance on the training and/or testing dataset, printing metrics such as accuracy, classification report, and confusion matrix.

7. **Model Saving and Loading**:
   - The `save_model` and `load_model` methods enable saving and loading the trained model using Python's `pickle` module.

8. **Predictions**:
   - The `predict` method generates predictions for new data using the trained model.

9. **Example Usage**:
   - Demonstrates how to use the class to prepare data, train the model, evaluate its performance, and save it for future use.

---





"""

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    classification_report,
    accuracy_score,
    confusion_matrix
)
import pickle
from pathlib import Path
import warnings
warnings.filterwarnings('ignore')

class BinaryClassificationProcessor:
    """
    A class to handle binary classification processing for vehicle state.
    """

    def __init__(self, data):
        """
        Initialize the binary classification processor.

        Parameters:
        -----------
        data : pd.DataFrame
            Preprocessed vehicle data
        """
        self.data = data.copy()
        self.X_train = None
        self.X_test = None
        self.y_train = None
        self.y_test = None
        self.model = None

    def prepare_target(self):
        """
        Prepare the target variable by encoding trouble codes.
        """
        # Display initial distribution of trouble codes
        print("Initial TROUBLE_CODES distribution:")
        print(self.data['TROUBLE_CODES'].value_counts())
        print("\n")

        # Encode trouble codes as binary (0 for normal, 1 for issues)
        self.data['T_C'] = self.data['TROUBLE_CODES'].apply(
            lambda x: 0 if x == 'normal' else 1
        )

        print("Binary encoded distribution:")
        print(self.data['T_C'].value_counts())
        print("\n")

    def balance_dataset(self, normal_sample_size=23214, random_state=42):
        """
        Balance the dataset using undersampling.

        Parameters:
        -----------
        normal_sample_size : int
            Number of normal cases to keep
        random_state : int
            Random state for reproducibility
        """
        # Undersample the majority class (normal cases)
        normal_indices = self.data[
            self.data['TROUBLE_CODES'] == 'normal'
        ].sample(n=normal_sample_size, random_state=random_state).index

        self.data = self.data.drop(normal_indices)

        print("Balanced dataset distribution:")
        print(self.data['T_C'].value_counts())
        print("\n")

    def prepare_features(self, additional_drops=None):
        """
        Prepare features for modeling.

        Parameters:
        -----------
        additional_drops : list
            Additional columns to drop from features
        """
        # Default columns to drop
        drops = ['T_C', 'TROUBLE_CODES', 'HOURS']

        # Add any additional columns to drop
        if additional_drops:
            drops.extend(additional_drops)

        # Prepare features and target
        self.X = self.data.drop(drops, axis=1)
        self.y = self.data['T_C']

    def split_data(self, test_size=0.2, random_state=42):
        """
        Split the data into training and testing sets.

        Parameters:
        -----------
        test_size : float
            Proportion of dataset to include in the test split
        random_state : int
            Random state for reproducibility
        """
        self.X_train, self.X_test, self.y_train, self.y_test = train_test_split(
            self.X, self.y, test_size=test_size, random_state=random_state
        )

    def train_model(self, **model_params):
        """
        Train the Random Forest model.

        Parameters:
        -----------
        **model_params : dict
            Parameters to pass to RandomForestClassifier
        """
        self.model = RandomForestClassifier(**model_params)
        self.model.fit(self.X_train, self.y_train)

    def evaluate_model(self, dataset='both'):
        """
        Evaluate the model performance.

        Parameters:
        -----------
        dataset : str
            Which dataset to evaluate ('train', 'test', or 'both')
        """
        def get_metrics(X, y, dataset_name):
            pred = self.model.predict(X)
            clf_report = pd.DataFrame(
                classification_report(y, pred, output_dict=True)
            )

            print(f"{dataset_name} Results:")
            print("=" * 50)
            print(f"Accuracy Score: {accuracy_score(y, pred) * 100:.2f}%")
            print("_" * 50)
            print(f"Classification Report:\n{clf_report}")
            print("_" * 50)
            print(f"Confusion Matrix:\n{confusion_matrix(y, pred)}\n")

        if dataset.lower() in ['train', 'both']:
            get_metrics(self.X_train, self.y_train, "Training")

        if dataset.lower() in ['test', 'both']:
            get_metrics(self.X_test, self.y_test, "Testing")

    def save_model(self, filename='binary_model.sav'):
        """
        Save the trained model to disk.

        Parameters:
        -----------
        filename : str
            Name of the file to save the model
        """
        pickle.dump(self.model, open(filename, 'wb'))
        print(f"Model saved as {filename}")

    def load_model(self, filename='binary_model.sav'):
        """
        Load a trained model from disk.

        Parameters:
        -----------
        filename : str
            Name of the file containing the saved model
        """
        self.model = pickle.load(open(filename, 'rb'))
        print(f"Model loaded from {filename}")

    def predict(self, X):
        """
        Make predictions using the trained model.

        Parameters:
        -----------
        X : pd.DataFrame
            Features to make predictions on

        Returns:
        --------
        np.array
            Predicted classes
        """
        return self.model.predict(X)

# usage
if __name__ == "__main__":
    # Assuming 'data' is your preprocessed DataFrame
    classifier = BinaryClassificationProcessor(data)

    # Prepare data
    classifier.prepare_target()
    classifier.balance_dataset()
    classifier.prepare_features()
    classifier.split_data()

    # Train and evaluate model
    classifier.train_model(random_state=42)
    classifier.evaluate_model(dataset='both')

    # Save model
    classifier.save_model()

    # Make predictions on new data
    # new_predictions = classifier.predict(new_data)

"""This script defines a `CGANDataGenerator` class, which uses Conditional GANs to generate synthetic data for oversampling and balancing a dataset containing vehicle-related metrics, including trouble codes and hours. Here's a breakdown of its functionality:

### Key Features
1. **Data Preprocessing**:
   - Scales continuous features using `StandardScaler`.
   - Encodes categorical labels (`TROUBLE_CODES`) using `OneHotEncoder`.

2. **CGAN Model Architecture**:
   - **Generator**: Generates synthetic data based on noise and encoded trouble codes.
   - **Discriminator**: Evaluates the authenticity of the input data.
   - **CGAN**: Combines the generator and discriminator into a conditional GAN for training.

3. **Training Process**:
   - Trains the generator and discriminator alternately.
   - Ensures the discriminator learns to distinguish real from synthetic data while the generator improves to produce realistic data.

4. **Synthetic Data Generation**:
   - After training, the generator can create synthetic samples conditioned on specific trouble codes.

"""

from sklearn.preprocessing import StandardScaler, OneHotEncoder
from tensorflow.keras.models import Sequential, Model
from tensorflow.keras.layers import Dense, LeakyReLU, BatchNormalization, Input, concatenate
from tensorflow.keras.optimizers import Adam
import tensorflow as tf

class CGANDataGenerator:
    """
    A class to handle data generation using Conditional GAN for oversampling vehicle data.
    """

    def __init__(self, data, trouble_code_col='TROUBLE_CODES', hours_col='HOURS'):
        """
        Initialize the CGAN data generator.

        Parameters:
        -----------
        data : pd.DataFrame
            Input data containing features and trouble codes
        trouble_code_col : str
            Name of the trouble codes column
        hours_col : str
            Name of the hours column
        """
        self.data = data.copy()
        self.trouble_code_col = trouble_code_col
        self.hours_col = hours_col

        self.scaler = StandardScaler()
        self.encoder = OneHotEncoder(sparse_output=False)

        self.generator = None
        self.discriminator = None
        self.cgan = None

        self.latent_dim = 100
        self.features_scaled = None
        self.trouble_codes_encoded = None
        self.combined_data = None

    def preprocess_data(self):
        """
        Preprocess the data by scaling features and encoding trouble codes.
        """
        # Separate features and targets
        self.features = self.data.drop(columns=[self.trouble_code_col, self.hours_col])
        self.trouble_codes = self.data[self.trouble_code_col]
        self.hours = self.data[self.hours_col]

        # Scale features
        self.features_scaled = self.scaler.fit_transform(self.features)

        # Encode trouble codes
        self.trouble_codes_encoded = self.encoder.fit_transform(
            self.trouble_codes.values.reshape(-1, 1)
        )

        # Combine data
        self.combined_data = np.hstack((
            self.features_scaled,
            self.trouble_codes_encoded,
            self.hours.values.reshape(-1, 1)
        ))

        self.num_classes = self.trouble_codes_encoded.shape[1]
        self.num_features = self.combined_data.shape[1]

    def build_generator(self):
        """
        Build the generator model.
        """
        noise_input = Input(shape=(self.latent_dim,))
        label_input = Input(shape=(self.num_classes,))
        merged_input = concatenate([noise_input, label_input])

        x = Dense(128)(merged_input)
        x = LeakyReLU(alpha=0.01)(x)
        x = BatchNormalization(momentum=0.8)(x)

        x = Dense(256)(x)
        x = LeakyReLU(alpha=0.01)(x)
        x = BatchNormalization(momentum=0.8)(x)

        x = Dense(self.num_features)(x)

        self.generator = Model([noise_input, label_input], x, name='Generator')

    def build_discriminator(self):
        """
        Build the discriminator model.
        """
        data_input = Input(shape=(self.num_features,))
        label_input = Input(shape=(self.num_classes,))
        merged_input = concatenate([data_input, label_input])

        x = Dense(512)(merged_input)
        x = LeakyReLU(alpha=0.01)(x)

        x = Dense(256)(x)
        x = LeakyReLU(alpha=0.01)(x)

        x = Dense(128)(x)
        x = LeakyReLU(alpha=0.01)(x)

        output = Dense(1, activation='sigmoid')(x)

        self.discriminator = Model([data_input, label_input], output, name='Discriminator')
        self.discriminator.compile(
            loss='binary_crossentropy',
            optimizer=Adam(learning_rate=0.0002, beta_1=0.5),
            metrics=['accuracy']
        )

    def build_cgan(self):
        """
        Build the combined CGAN model.
        """
        self.discriminator.trainable = False

        noise_input = Input(shape=(self.latent_dim,))
        label_input = Input(shape=(self.num_classes,))

        gen_data = self.generator([noise_input, label_input])
        validity = self.discriminator([gen_data, label_input])

        self.cgan = Model([noise_input, label_input], validity, name='CGAN')
        self.cgan.compile(
            loss='binary_crossentropy',
            optimizer=Adam(learning_rate=0.0002, beta_1=0.5)
        )

    def train(self, epochs=10000, batch_size=32, verbose=True):
        """
        Train the CGAN model.

        Parameters:
        -----------
        epochs : int
            Number of training epochs
        batch_size : int
            Size of training batches
        verbose : bool
            Whether to print training progress
        """
        valid = np.ones((batch_size, 1))
        fake = np.zeros((batch_size, 1))

        for epoch in range(epochs):
            # Train Discriminator
            idx = np.random.randint(0, self.combined_data.shape[0], batch_size)
            real_data = self.combined_data[idx]
            real_labels = self.trouble_codes_encoded[idx]

            noise = np.random.normal(0, 1, (batch_size, self.latent_dim))
            gen_data = self.generator.predict([noise, real_labels], verbose=0)

            d_loss_real = self.discriminator.train_on_batch(
                [real_data, real_labels], valid
            )
            d_loss_fake = self.discriminator.train_on_batch(
                [gen_data, real_labels], fake
            )
            d_loss = 0.5 * np.add(d_loss_real, d_loss_fake)

            # Train Generator
            noise = np.random.normal(0, 1, (batch_size, self.latent_dim))
            g_loss = self.cgan.train_on_batch([noise, real_labels], valid)

            if verbose and epoch % 100 == 0:
                print(
                    f"Epoch {epoch}/{epochs} "
                    f"[D loss: {d_loss[0]:.4f}, acc: {100*d_loss[1]:.2f}%] "
                    f"[G loss: {g_loss:.4f}]"
                )

    def generate_synthetic_data(self, num_samples):
        """
        Generate synthetic data using the trained generator.

        Parameters:
        -----------
        num_samples : int
            Number of synthetic samples to generate

        Returns:
        --------
        pd.DataFrame
            DataFrame containing the generated synthetic data
        """
        # Generate noise and sample labels
        noise = np.random.normal(0, 1, (num_samples, self.latent_dim))
        sampled_labels = np.random.choice(
            self.encoder.categories_[0],
            num_samples
        )
        sampled_labels = self.encoder.transform(sampled_labels.reshape(-1, 1))

        # Generate synthetic data
        synthetic_data = self.generator.predict([noise, sampled_labels], verbose=0)

        # Separate features and create DataFrame
        synthetic_trouble_codes = self.encoder.inverse_transform(sampled_labels)
        synthetic_hours = synthetic_data[:, -1]
        synthetic_features = synthetic_data[:, :-self.num_classes-1]

        # Create DataFrame with original feature names
        synthetic_df = pd.DataFrame(
            self.scaler.inverse_transform(synthetic_features),
            columns=self.features.columns
        )
        synthetic_df[self.trouble_code_col] = synthetic_trouble_codes.flatten()
        synthetic_df[self.hours_col] = synthetic_hours

        return synthetic_df

# usage
if __name__ == "__main__":
    # Initialize generator
    data_generator = CGANDataGenerator(data_2)

    # Preprocess data
    data_generator.preprocess_data()

    # Build and train models
    data_generator.build_generator()
    data_generator.build_discriminator()
    data_generator.build_cgan()

    # Train the CGAN
    data_generator.train(epochs=10000, batch_size=32)

    # Generate synthetic data
    synthetic_data = data_generator.generate_synthetic_data(num_samples=2600)

    print("Original data shape:", data_generator.data.shape)
    print("Synthetic data shape:", synthetic_data.shape)

    # Combine original and synthetic data if needed
    combined_data = pd.concat([data_generator.data, synthetic_data], axis=0)

synthetic_data.to_csv('synthetic_data.csv', index=False)

synthetic_data.info()

synthetic_data['TROUBLE_CODES'].unique()

combined_data.info()

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import pickle

class TroubleCodeClassifier:
    def __init__(self):
        # Define the label mapping for trouble codes
        self.label_mapping = {
            'P0133': 0,
            'C0300': 1,
            'P0079P2004P3000': 2,
            'P0078U1004P3000': 3,
            'P0079C1004P3000': 4,
            'P007EP2036P18F0': 5,
            'P007EP2036P18D0': 6,
            'P007FP2036P18D0': 7,
            'P0079P1004P3000': 8,
            'P007EP2036P18E0': 9,
            'P007FP2036P18E0': 10,
            'P0078B0004P3000': 11,
            'P007FP2036P18F0': 12,
            'normal': 13
        }
        self.model = RandomForestClassifier(n_estimators=50, max_depth=7, random_state=42)

    def preprocess_data(self, synthetic_df, data_2):
        """
        Preprocess the datasets by balancing classes and combining them
        """
        size = int(len(synthetic_df)/3)
        normal_indices = synthetic_df[synthetic_df['TROUBLE_CODES'] == 'normal'].sample(n=size, random_state=42, replace = True).index
        synthetic_df = synthetic_df.drop(normal_indices)

        P0133_indices = synthetic_df[synthetic_df['TROUBLE_CODES'] == 'P0133'].sample(n=size+1, random_state=42, replace = True).index
        synthetic_df = synthetic_df.drop(P0133_indices)

        C0300_indices = synthetic_df[synthetic_df['TROUBLE_CODES'] == 'C0300'].sample(n=size - 11, random_state=42, replace = True).index
        synthetic_df = synthetic_df.drop(C0300_indices)

        # Balance the second dataset
        normal_indices = data_2[data_2['TROUBLE_CODES'] == 'normal'].sample(n=35214, random_state=42).index
        data_2 = data_2.drop(normal_indices)

        # Combine datasets
        df = pd.concat([data_2, synthetic_df], ignore_index=True)

        # Map trouble codes to numerical labels
        df['TROUBLE_CODES'] = df['TROUBLE_CODES'].map(self.label_mapping)

        # Prepare features and target
        X = df.drop(columns=['TROUBLE_CODES', 'HOURS'])
        y = df['TROUBLE_CODES']

        return X, y

    def train_model(self, X, y, test_size=0.2):
        """
        Train the model and print evaluation metrics
        """
        # Split the data
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=test_size, random_state=42)

        # Train the model
        self.model.fit(X_train, y_train)

        # Evaluate and print results
        self._print_evaluation(X_train, y_train, "Training")
        self._print_evaluation(X_test, y_test, "Testing")

        return X_train, X_test, y_train, y_test

    def _print_evaluation(self, X, y, dataset_type):
        """
        Print detailed evaluation metrics
        """
        predictions = self.model.predict(X)
        clf_report = pd.DataFrame(classification_report(y, predictions, output_dict=True))

        print(f"\n{dataset_type} Results:")
        print("=" * 50)
        print(f"Accuracy Score: {accuracy_score(y, predictions) * 100:.2f}%")
        print("\nClassification Report:")
        print(clf_report)

        # Optional: Print feature importances
        if hasattr(self.model, 'feature_importances_'):
            importances = pd.DataFrame({
                'feature': X.columns,
                'importance': self.model.feature_importances_
            }).sort_values('importance', ascending=False)
            print("\nTop 10 Most Important Features:")
            print(importances.head(10))

    def save_model(self, filename='Multi_Classification_Model2.sav'):
        """
        Save the trained model to disk
        """
        pickle.dump(self.model, open(filename, 'wb'))
        print(f"\nModel saved successfully as {filename}")

def main():
    # Initialize the classifier
    classifier = TroubleCodeClassifier()

    # Load your data here
    synthetic_df = combined_data.copy()

    # Preprocess and train
    X, y = classifier.preprocess_data(combined_data, combined_data)

    X_train, X_test, y_train, y_test = classifier.train_model(X, y)

    # Save the model
    classifier.save_model()

if __name__ == "__main__":
    main()

"""# Vehicle Hours Predictor Model

This demonstrates the development of a regression model to predict the number of hours a vehicle will run based on various features and associated trouble codes.

## Key Components
1. **Model Definition**:
   - An `ExtraTreesRegressor` is used with specific hyperparameters (`max_depth=25`, `n_estimators=30`).
   - A label mapping converts categorical trouble codes into numerical labels for processing.

2. **Data Preprocessing**:
   - Trouble codes are mapped to numerical values.
   - Features (`X`) and the target (`y`) are extracted from the dataset.

3. **Model Training and Evaluation**:
   - The dataset is split into training and testing sets.
   - The model is trained, and metrics such as MAE, MSE, RMSE, and R² are calculated for both sets.
   - Feature importance is analyzed to determine the most influential features.

4. **Model Saving and Loading**:
   - The trained model can be saved to a file and loaded for later use.
---
"""

from sklearn.model_selection import train_test_split
from sklearn.ensemble import ExtraTreesRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import pickle

class VehicleHoursPredictor:
    def __init__(self):
        # Define the label mapping for trouble codes
        self.label_mapping = {
            'normal': 0,
            'P0133': 1,
            'C0300': 2,
            'P0079P2004P3000': 3,
            'P0078U1004P3000': 4,
            'P0079C1004P3000': 5,
            'P007EP2036P18F0': 6,
            'P007EP2036P18D0': 7,
            'P007FP2036P18D0': 8,
            'P0079P1004P3000': 9,
            'P007EP2036P18E0': 10,
            'P007FP2036P18E0': 11,
            'P0078B0004P3000': 12,
            'P007FP2036P18F0': 13
        }
        self.model = ExtraTreesRegressor(max_depth=25, n_estimators=30, random_state=42)

    def preprocess_data(self, data):
        """
        Preprocess the dataset for hours prediction
        """
        # Create a copy to avoid modifying original data
        df = data.copy()

        # Map trouble codes to numerical labels
        df['TROUBLE_CODES'] = df['TROUBLE_CODES'].map(self.label_mapping)

        # Prepare features and target
        X = df.drop(columns=['HOURS', 'TROUBLE_CODES'])
        y = df['HOURS']

        return X, y

    def train_model(self, X, y, test_size=0.2):
        """
        Train the model and print evaluation metrics
        """
        # Split the data
        X_train, X_test, y_train, y_test = train_test_split(
            X, y, test_size=test_size, random_state=42
        )

        # Train the model
        self.model.fit(X_train, y_train)

        # Evaluate and print results
        self._print_evaluation(X_train, y_train, X_test, y_test)

        return X_train, X_test, y_train, y_test

    def _print_evaluation(self, X_train, y_train, X_test, y_test):
        """
        Print detailed evaluation metrics for both training and testing sets
        """
        # Training metrics
        train_pred = self.model.predict(X_train)
        train_metrics = self._calculate_metrics(y_train, train_pred)

        # Testing metrics
        test_pred = self.model.predict(X_test)
        test_metrics = self._calculate_metrics(y_test, test_pred)

        # Print results
        print("\nTraining Results:")
        print("=" * 50)
        self._print_metrics(train_metrics)

        print("\nTesting Results:")
        print("=" * 50)
        self._print_metrics(test_metrics)

        # Print feature importances
        self._print_feature_importance(X_train)

    def _calculate_metrics(self, y_true, y_pred):
        """
        Calculate regression metrics
        """
        return {
            'MAE': mean_absolute_error(y_true, y_pred),
            'MSE': mean_squared_error(y_true, y_pred),
            'RMSE': np.sqrt(mean_squared_error(y_true, y_pred)),
            'R2': r2_score(y_true, y_pred)
        }

    def _print_metrics(self, metrics):
        """
        Print formatted metrics
        """
        print(f"Mean Absolute Error: {metrics['MAE']:.2f}")
        print(f"Mean Squared Error: {metrics['MSE']:.2f}")
        print(f"Root Mean Squared Error: {metrics['RMSE']:.2f}")
        print(f"R-squared Score: {metrics['R2']:.4f}")

    def _print_feature_importance(self, X):
        """
        Print feature importance analysis
        """
        importances = pd.DataFrame({
            'feature': X.columns,
            'importance': self.model.feature_importances_
        }).sort_values('importance', ascending=False)

        print("\nTop 10 Most Important Features:")
        print(importances.head(10))

    def predict(self, X):
        """
        Make predictions on new data
        """
        return self.model.predict(X)

    def save_model(self, filename='Regression_Hours_Model.sav'):
        """
        Save the trained model to disk
        """
        pickle.dump(self.model, open(filename, 'wb'))
        print(f"\nModel saved successfully as {filename}")

    @staticmethod
    def load_model(filename='Regression_Hours_Model.sav'):
        """
        Load a saved model
        """
        return pickle.load(open(filename, 'rb'))

def main():
    # Initialize the predictor
    predictor = VehicleHoursPredictor()

    # Load your data here
    # data_3 = pd.read_csv('your_data.csv')

    # Preprocess and train
    X, y = predictor.preprocess_data(combined_data)
    X_train, X_test, y_train, y_test = predictor.train_model(X, y)

    # Save the model
    predictor.save_model()

if __name__ == "__main__":
    main()

combined_data.head()